haxball/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^leagues/', include('leagues.urls', namespace='leagues')),
    url(r'^captcha/', include('captcha.urls')),
)

leagues/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns('',
    url(r'^$', 'leagues.views.index', name='index'),
    url(r'^(?P<league_id>\d+)/$', 'leagues.views.detail', name='detail'),
    url(r'^(?P<league_id>\d+)/pass/$', 'leagues.views.admin_pass', name='pass'),
    url(r'^(?P<result_id>\d+)/set_score/$', 'leagues.views.set_score', name='set_score'),
    url(r'^(?P<result_id>\d+)/clear_score/$', 'leagues.views.clear_score', name='clear_score'),
    url(r'^(?P<result_id>\d+)/set_replay/$', 'leagues.views.set_replay', name='set_replay'),
    url(r'^(?P<league_id>\d+)/edit_names/$', 'leagues.views.edit_names', name='edit_names'),
    url(r'^(?P<league_id>\d+)/delete/$', 'leagues.views.delete', name='delete'),
    url(r'^latest/$', 'leagues.views.latest', name='latest'),
)

leagues/models.py
from django.db import models
from django_countries import CountryField

ROUNDS_TYPE = (
    (1, 'Round Robin'),
    (2, 'Double Round Robin'),
)

class Description(models.Model):
    name = models.CharField(max_length=30)
    password = models.CharField(max_length=30)
    teams = models.IntegerField()
    rounds = models.IntegerField(default=2, choices=ROUNDS_TYPE)
    country = CountryField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __unicode__(self):
        return u'%s' % self.name
    
class Contestants(models.Model):
    league = models.ForeignKey(Description)
    name = models.CharField(max_length=20)
    match = models.IntegerField(default=0)
    win = models.IntegerField(default=0)
    draw = models.IntegerField(default=0)
    loss = models.IntegerField(default=0)
    goal_for = models.IntegerField(default=0)
    goal_against = models.IntegerField(default=0)
    points = models.IntegerField(default=0)
    
    def __unicode__(self):
        return u'%s' % self.name
    
class Results(models.Model):
    league = models.ForeignKey(Description)
    contestant1 = models.ForeignKey(Contestants, related_name="contestant1")
    contestant2 = models.ForeignKey(Contestants, related_name="contestant2")
    result1 = models.IntegerField(default=-1)
    result2 = models.IntegerField(default=-1)
    replay = models.IntegerField(default=0)
    updated = models.DateTimeField(auto_now=True)
    
    def __unicode__(self):
        return u'%s %s' % (self.contestant1, self.contestant2)
    

leagues/forms.py
from django import forms
from django.forms.formsets import BaseFormSet
from django.forms.models import BaseInlineFormSet
from leagues.models import Description, Contestants, Results
from captcha.fields import CaptchaField

class DescriptionForm(forms.ModelForm):
    repeat = forms.CharField(label='Repeat password')
    
    """
    https://django-simple-captcha.readthedocs.org/en/latest/usage.html#define-the-form
    """
    captcha = CaptchaField()
    
    def clean(self):
        super(DescriptionForm,self).clean()
        if 'password' in self.cleaned_data and 'repeat' in self.cleaned_data:
            password = self.cleaned_data['password']
            repeat = self.cleaned_data['repeat']
            
            if password != repeat:
                self._errors['repeat'] = [u'Password didnt match']
                
        return self.cleaned_data
    
    class Meta:
        model = Description
        fields = ('name', 'password', 'repeat', 'rounds', 'captcha',)

class ContestantsForm(forms.ModelForm):
    name = forms.CharField(label='Team name')
    
    class Meta:
        model = Contestants
        fields = ('name',)
        #exclude = ('tournament', 'match', 'win', 'draw', 'loss', 'goal_for', 'goal_against', 'points')
        
class ResultsForm(forms.ModelForm):
    result1 = forms.IntegerField(label='Home')
    result2 = forms.IntegerField(label='Away')

    def clean(self):
        super(ResultsForm,self).clean()
        if 'result1' in self.cleaned_data and 'result2' in self.cleaned_data:
            result1 = self.cleaned_data['result1']
            result2 = self.cleaned_data['result2']
            
            if result1 > 99:
                self._errors['result1'] = [u'Max. 99!']
            elif result1 < 0:
                self._errors['result1'] = [u'Min. 0!']
                
            if result2 > 99:
                self._errors['result2'] = [u'Max. 99!']
            elif result2 < 0:
                self._errors['result2'] = [u'Min. 0!']
                
        return self.cleaned_data
    
    class Meta:
        model = Results
        fields = ('result1', 'result2',)
        #exclude = ('tournament', 'contestant1', 'contestant2', 'replay', 'updated')
        
class UploadForm(forms.Form):
    replay = forms.FileField()
    
    def clean_replay(self):
        max_size = 5*10**4
        file_name = self.cleaned_data['replay'].name
        
        if self.cleaned_data['replay'].size > max_size:
            self._errors['replay'] = [u'Max. file size: 50 kB']
        elif file_name.split('.')[1] != 'hbr':
            self._errors['replay'] = [u'You can only upload files with the .hbr extension!']
            
        return self.cleaned_data['replay']
        
"""
This class is used to make empty formset forms required
See http://stackoverflow.com/questions/2406537/django-formsets-make-first-required/4951032#4951032
"""
class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False
    
    """
    https://docs.djangoproject.com/en/dev/topics/forms/formsets/#custom-formset-validation
    """            
    def clean(self):
        """Checks that no two teams have the same name."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        names = []
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            name = form.cleaned_data['name']
            if name in names:
                raise forms.ValidationError("Teams must have different names!")
            names.append(name)
            
class Required2FormSet(BaseInlineFormSet):
                
    def clean(self):
        """Checks that no two teams have the same name."""
        if any(self.errors):
            # Don't bother validating the formset unless each form is valid on its own
            return
        names = []
        for i in range(0, self.total_form_count()):
            form = self.forms[i]
            name = form.cleaned_data['name']
            if name in names:
                raise forms.ValidationError("Teams must have different names!")
            names.append(name)

leagues/views.py
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404, render

from leagues.models import Description, Contestants, Results
from leagues.forms import DescriptionForm, ContestantsForm, ResultsForm, UploadForm, RequiredFormSet, Required2FormSet
from leagues.tools import create_schedule, handle_uploaded_file

from django.forms.formsets import formset_factory
from django.forms.models import inlineformset_factory

from django.contrib.gis.geoip import GeoIP
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

import struct

def index(request):
    last_leagues = Description.objects.all().order_by('-id')[:10]
    user_ip_adress = request.META['REMOTE_ADDR']
    user_country = GeoIP().country_code('%s' % user_ip_adress)
    ContestantsFormSet = formset_factory(ContestantsForm, formset=RequiredFormSet, extra=4, max_num=10)
    
    if request.method == 'POST':
        description_form = DescriptionForm(request.POST)
        contestants_formset = ContestantsFormSet(request.POST)
        teams_num = contestants_formset.total_form_count()
        if description_form.is_valid() and contestants_formset.is_valid() and teams_num >= 4 and teams_num < 21:
            human = True
            
            description = description_form.save(commit=False)
            description.teams = teams_num
            description.country = user_country
            description.save()
            
            # save contestant to list
            team_ids = []
            for form in contestants_formset.forms:
                contestants = form.save(commit=False)
                contestants.league = description
                contestants.save()
                team_ids.append(contestants)
                
            # create pairs and add match
            for round in create_schedule(team_ids, description.rounds):
                for match in round:
                    if match[0] != "BYE" and match[1] != "BYE":
                        add_match = Results(league=description, contestant1=match[0], contestant2=match[1])
                        add_match.save()
                        
            # save league id to cookie
            request.session['league_id'] = description.id
            request.session.set_expiry(3600)
                
            return HttpResponseRedirect(reverse('leagues:detail', args=(description.id,)))
    else:
        description_form = DescriptionForm()
        contestants_formset = ContestantsFormSet()
        teams_num = contestants_formset.total_form_count()
        
    return render(request, 'leagues/index.html', {'description_form': description_form, 'contestants_formset': contestants_formset, 'teams_num': teams_num, 'last_leagues': last_leagues})

def detail(request, league_id):
    league = get_object_or_404(Description, pk=league_id)
    get_results = Results.objects.filter(league=league_id).order_by('id')
    get_contestants = Contestants.objects.extra(select={'diff': 'goal_for - goal_against'}, where=['league_id=%s'], params=[league_id]).order_by('-points', '-diff', 'id')
    can_edit_and_delete = False
    
    if request.session.get('league_id', False) and request.session['league_id'] == int(league_id):
        can_edit_and_delete = True
        
    return render(request, 'leagues/detail.html', {'visible': can_edit_and_delete, 'league': league, 'all_results': get_results, 'all_contestants': get_contestants})

def admin_pass(request, league_id):
    league = get_object_or_404(Description, pk=league_id)
    
    if request.method != 'POST' or 'admin_pass' not in request.POST:
        raise Http404('Only POST method!')
        
    if request.POST['admin_pass'] == league.password:
        request.session['league_id'] = int(league_id)
        request.session.set_expiry(3600)
        
    return HttpResponseRedirect(reverse('leagues:detail', args=(league.id,)))
    
def set_score(request, result_id):
    results = get_object_or_404(Results, pk=result_id)
    
    old_result1 = results.result1
    old_result2 = results.result2
    
    if request.session.get('league_id', False) and request.session['league_id'] == results.league.id:
        if request.method == 'POST':
            form = ResultsForm(request.POST, instance=results)
            if form.is_valid():
                new_result1 = results.result1
                new_result2 = results.result2
                
                if old_result1 and old_result2 < 0:
                    if form.instance.result1 > form.instance.result2:
                        form.instance.contestant1.match += 1
                        form.instance.contestant1.win += 1
                        form.instance.contestant1.goal_for += new_result1
                        form.instance.contestant1.goal_against += new_result2
                        form.instance.contestant1.points += 3
                        form.instance.contestant1.save()
                        
                        form.instance.contestant2.match += 1
                        form.instance.contestant2.loss += 1
                        form.instance.contestant2.goal_for += new_result2
                        form.instance.contestant2.goal_against += new_result1
                        #form.instance.contestant2.points -= 0 - not required
                        form.instance.contestant2.save()
                        
                    elif form.instance.result2 > form.instance.result1:
                        form.instance.contestant2.match += 1
                        form.instance.contestant2.win += 1
                        form.instance.contestant2.goal_for += new_result2
                        form.instance.contestant2.goal_against += new_result1
                        form.instance.contestant2.points += 3
                        form.instance.contestant2.save()
                        
                        form.instance.contestant1.match += 1
                        form.instance.contestant1.loss += 1
                        form.instance.contestant1.goal_for += new_result1
                        form.instance.contestant1.goal_against += new_result2
                        #form.instance.contestant1.points -= 0 - not required
                        form.instance.contestant1.save()
                        
                    elif form.instance.result1 == form.instance.result2:
                        form.instance.contestant1.match += 1
                        form.instance.contestant1.draw += 1
                        form.instance.contestant1.goal_for += new_result1
                        form.instance.contestant1.goal_against += new_result2
                        form.instance.contestant1.points += 1
                        form.instance.contestant1.save()
                        
                        form.instance.contestant2.match += 1
                        form.instance.contestant2.draw += 1
                        form.instance.contestant2.goal_for += new_result2
                        form.instance.contestant2.goal_against += new_result1
                        form.instance.contestant2.points += 1
                        form.instance.contestant2.save()
                        
                else:
                    
                    if old_result1 > old_result2 and new_result1 > new_result2:
                        form.instance.contestant1.goal_for += new_result1 - old_result1
                        form.instance.contestant1.goal_against += new_result2 - old_result2
                        form.instance.contestant1.save()
                        
                        form.instance.contestant2.goal_for += new_result2 - old_result2
                        form.instance.contestant2.goal_against += new_result1 - old_result1
                        form.instance.contestant2.save()
                    elif old_result1 > old_result2 and new_result1 < new_result2:
                        form.instance.contestant1.win -= 1
                        form.instance.contestant1.loss += 1
                        form.instance.contestant1.goal_for += new_result1 - old_result1
                        form.instance.contestant1.goal_against += new_result2 - old_result2
                        form.instance.contestant1.points -= 3
                        form.instance.contestant1.save()
                        
                        form.instance.contestant2.loss -= 1
                        form.instance.contestant2.win += 1
                        form.instance.contestant2.goal_for += new_result2 - old_result2
                        form.instance.contestant2.goal_against += new_result1 - old_result1
                        form.instance.contestant2.points += 3
                        form.instance.contestant2.save()
                    elif old_result1 > old_result2 and new_result1 == new_result2:
                        form.instance.contestant1.win -= 1
                        form.instance.contestant1.draw += 1
                        form.instance.contestant1.goal_for += new_result1 - old_result1
                        form.instance.contestant1.goal_against += new_result2 - old_result2
                        form.instance.contestant1.points -= 2
                        form.instance.contestant1.save()
                        
                        form.instance.contestant2.loss -= 1
                        form.instance.contestant2.draw += 1
                        form.instance.contestant2.goal_for += new_result2 - old_result2
                        form.instance.contestant2.goal_against += new_result1 - old_result1
                        form.instance.contestant2.points += 1
                        form.instance.contestant2.save()
                    
                    
                    if old_result2 > old_result1 and new_result2 > new_result1:
                        form.instance.contestant2.goal_for += new_result2 - old_result2

templates/leagues/base.html
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}/css/style.css" media="screen"/>
<title>HaxBall League</title>
<script type="text/javascript"
src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js">
</script>
<script type="text/javascript">
$(document).ready(function () {
    // Code adapted from http://djangosnippets.org/snippets/1389/  
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+-)');
        var replacement = prefix + '-' + ndx + '-';
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
        replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
    }
    function deleteForm(btn, prefix) {
        var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        if (formCount > 1) {
            // Delete the item/form
            $(btn).parents('.item').remove();
            var forms = $('.item'); // Get all the forms  
            // Update the total number of forms (1 less than before)
            $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
            var i = 0;
            // Go through the forms and set their indices, names and IDs
            for (formCount = forms.length; i < formCount; i++) {
                $(forms.get(i)).children().children().each(function () {
                    if ($(this).attr('type') == 'text') updateElementIndex(this, prefix, i);
                });
            }
        } // End if
        else {
            alert("You have to enter at least one team item!");
        }
        return false;
    }
    function addForm(btn, prefix) {
        var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        // You can only submit a maximum of 10 todo items 
        if (formCount < 20) {
            // Clone a form (without event handlers) from the first form
            var row = $(".item:first").clone(false).get(0);
            // Insert it after the last form
            $(row).removeAttr('id').hide().insertAfter(".item:last").slideDown(300);
            // Remove the bits we don't want in the new row/form
            // e.g. error messages
            $(".errorlist", row).remove();
            $(row).children().removeClass("error");
            // Relabel or rename all the relevant bits
            $(row).children().children().each(function () {
                updateElementIndex(this, prefix, formCount);
                $(this).val("");
            });
            // Add an event handler for the delete item/form link 
            $(row).find(".delete").click(function () {
                return deleteForm(this, prefix);
            });
            // Update the total form count
            $("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1);
        } // End if
        else {
            alert("Sorry, you can only enter a maximum of twenty items.");
        }
        return false;
    }
    // Register the click event handlers
    $("#add").click(function () {
        return addForm(this, "form");
    });
    $(".delete").click(function () {
        return deleteForm(this, "form");
    });
});
</script>
</head>
<body>
<div id="site-wrapper">

    {% block header %}
    <div id="header">

		<div id="top">

			<div id="logo">
				<a href="{% url 'leagues:index' %}"><img src="{{ STATIC_URL }}/img/hax_logo3.png" alt="" /></a>
			</div>

		</div>

	</div>
    {% endblock %}
    
    {% block content %}{% endblock %}
    
    {% block footer %}
    <div id="footer">

		<div class="left" id="footer-left">
			<p class="large"> <a href="{% url 'leagues:index' %}">Home</a> <span class="text-separator">|</span> <a href="{% url 'leagues:latest' %}">Latest leagues</a> <span class="text-separator">|</span> <strong><a href="https://github.com/slunzok/haxball-league">Source code!</a></strong> <span class="text-separator">|</span></p>
			<div class="clearer">&nbsp;</div>
		</div>

		<div class="right" id="footer-right">
		    <p>&copy; 2013 <a href="https://github.com/slunzok/">slunzok</a></p>
			<p class="quiet"><a href="http://templates.arcsin.se/">Website template</a> by <a href="http://arcsin.se/">Arcsin</a></p>
		</div>

		<div class="clearer">&nbsp;</div>

	</div>
    {% endblock %}

</div>
</body>
</html>

templates/leagues/clear_score.html
{% extends "leagues/base.html" %}

{% block content %}

    <div id="splash">
	
	    <div class="col5 left">
	    
            <h2 class="label label-blue">Clear score</h2><br />
            
                <form action="" method="post">{% csrf_token %}
                <input class="login2" type="submit" name="submit" value="Do it!" />
                </form>

		</div>

		<div class="clearer">&nbsp;</div>

	</div>

{% endblock %}

templates/leagues/delete.html
{% extends "leagues/base.html" %}

{% block content %}

    <div id="splash">
	
	    <div class="col5 left">
	    
            <h2 class="label label-blue">Delete league</h2><br />
            
            <form action="" method="post">{% csrf_token %}
            <input class="login2" type="submit" name="submit" value="Do it!" />
            </form> 
            
		</div>

		<div class="clearer">&nbsp;</div>

	</div>

{% endblock %}

templates/leagues/detail.html
{% extends "leagues/base.html" %}

{% load divide %}

{% block content %}

    <div id="splash">
	
	    <div class="col5 left">
			
			<h2 class="label label-blue">{{ league.name }}</h2><br />
			<p class="quiet large"><img src="{{ league.country.flag }}"> Created: {{ league.created|date:"d.m.Y H:i" }} &nbsp; - &nbsp; Teams: {{ league.teams }} &nbsp; - &nbsp; System: {% if league.rounds == 1 %}Single{% else %}Double{% endif %} Round Robin</p>
			
			{% if visible %}
                <p><strong><a href="{% url 'leagues:edit_names' league.id %}">Edit team names</a></strong> &nbsp; &nbsp; <strong><a href="{% url 'leagues:delete' league.id %}">Delete league</a></strong></p>
            {% else %}
                <form action="{% url 'leagues:pass' league.id %}" method="post">
                {% csrf_token %}
                <p><label class="detail">Please enter the password in order to edit the results: </label><input type="text" name="admin_pass" id="haslo" value="" /><input type="submit" value="Send" class="detail" /></p>
                </form><br /><br />
            {% endif %}
            
			<table class="data-table">
				<tr>
					<th></th>
					<th>Team</th>
					<th><abbr title="Played">P</abbr></th>
					<th><abbr title="Won">W</abbr></th>
					<th><abbr title="Draw">D</abbr></th>
					<th><abbr title="Lost">L</abbr></th>
					<th><abbr title="Goals">G</abbr></th>
					
					<th><abbr title="Goal difference">+/-</abbr></th>
					<th><abbr title="Points">Pts</abbr></th>
				</tr>
            {% for contestant in all_contestants %}
                {% if not forloop.counter|divisibleby:2 %}
                <tr class="even">
                {% else %}
                <tr>
                {% endif %}
                    <td>{{ forloop.counter }}</td>
                    <td style="width: 20%">{{ contestant.name }}</td>
                    <td>{{ contestant.match }}</td>
                    <td>{{ contestant.win }}</td>
                    <td>{{ contestant.draw }}</td>
                    <td>{{ contestant.loss }}</td>
                    <td>{{ contestant.goal_for }}:{{ contestant.goal_against }}</td>
                    <td>{{ contestant.diff }}</td>
                    <td>{{ contestant.points }}</td>
                    </tr>
            {% endfor %}
			</table>
			
			{% for result in all_results %}
                {% with pairs=league.teams|div:2 %}
                    {% if forloop.counter0|divisibleby:pairs %}
                        {% with count=forloop.counter0|div:pairs %}
                            <p class="label label-orange">Fixture {{ count|add:1 }}</p><br />
                            <table class="data-table2">
                                <tr>
					                <th>Replay</th>
					                <th>Red Team</th>
                                    <th>Score</th>
                                    <th>Blue Team</th>
                                    {% if visible %}<th>Admin</th>{% else %}<th>Updated</th>{% endif %}
				                </tr>
                        {% endwith %}
                    {% endif %}
                {% endwith %}
        
                {% if not forloop.counter|divisibleby:2 %}
                    <tr class="even">
                {% else %}
                    <tr>
                {% endif %}
                    <td>{% if result.replay == 1 %}{% if visible %}<abbr title="This action overwrite previous replay!"><img src="{{ STATIC_URL}}/img/red_circle2.png" /></abbr> <a href="{% url 'leagues:set_replay' result.id %}">Set replay</a>{% else %}<a href="{{ MEDIA_URL }}replays/league_{{ result.id }}.hbr">Watch</a>{% endif %} {% else %} {% if visible %}{% if result.result1 >= 0 and result.result2 >= 0 %}<abbr title="First upload, OK :)"><img src="{{ STATIC_URL }}/img/green_circle2.png" /></abbr> <a href="{% url 'leagues:set_replay' result.id %}">Set replay</a>{% else %} - {% endif %}{% else %} - {% endif %}{% endif %}</td>
                    <td>{{ result.contestant1 }}</td>
                    <td>{% if result.result1 >= 0 and result.result2 >= 0 %}{{ result.result1 }} : {{ result.result2 }}{% else %} - {% endif %}</td>
                    <td>{{ result.contestant2 }}</td>
                    <td>{% if visible %}{% if result.result1 >= 0 and result.result2 >= 0 %}<a href="{% url 'leagues:clear_score' result.id %}">Clear score</a>{% else %}<a href="{% url 'leagues:set_score' result.id %}">Set score</a>{% endif %}{% else %}{% if result.result1 >= 0 and result.result2 >= 0 %}<span class=" quiet small">{{ result.updated|date:"d.m.Y H:i" }}</span>{% else %}<span class=" quiet small">-</span>{% endif %}{% endif %}</td>
                    </tr>
                    
                {% with pairs=league.teams|div:2 %}
                    {% if forloop.counter|divisibleby:pairs %}
                        </table>
                    {% endif %}
                {% endwith %}
    
            {% endfor %}

		</div>

		<div class="clearer">&nbsp;</div>

	</div>

{% endblock %}

templates/leagues/index.html
{% extends "leagues/base.html" %}

{% block content %}

    <div id="splash">
	
	    <div class="col3 left">
			
			<h2 class="label label-blue">New league</h2><br />

            <form action="" method="POST">{% csrf_token %}
            {% for field in description_form %}
                {% if field.errors %}
                    <div class="login_form_row">
                    {% if field.html_name == 'captcha' %}
                        <p>{{ field.label_tag }} {{ field }}</p>
                        <p><span class=" quiet small yuo">{{ field.errors.as_text }}</span></p>
                    {% else %}
                        <p>{{ field.label_tag }} <input id="id_{{ field.html_name }}" name="{{ field.html_name }}" type="text" class="rty" /></p>
                        <p><span class=" quiet small yuo">{{ field.errors.as_text }}</span></p>
                    {% endif %}
                    </div>
                {% else %}
                    <div class="login_form_row">
                    <p>{{ field.label_tag }} {{ field }}</p>
                    </div>
                {% endif %}
            {% endfor %}
    
            <div class="clearer">&nbsp;</div>
    
            {% if teams_num < 4 %}
                <p><span class="yuo2">* Minumum 4 teams</span></p>
            {% endif %}
            
            {% if teams_num > 20 %}
                <p><span class="yuo2">* Maximum 20 teams</span></p>
            {% endif %}
            
            {% if contestants_formset.non_form_errors %}
                <p><span class="yuo2">{{ contestants_formset.non_form_errors.as_text }}</span></p>
            {% endif %}
    
            {{ contestants_formset.management_form }}
            {% for form in contestants_formset.forms %}
                {% for field in form %}
                    {% if field.errors %}
                        <div class="item">
                        <p>{{ field.label_tag }} <input id="id_{{ field.html_name }}" name="{{ field.html_name }}" type="text" class="rty" /></p>
                        <p style="">&nbsp; &nbsp; &nbsp;<a class="delete" href="#">Delete</a></p>
                        <p><span class=" quiet small yuo">{{ field.errors.as_text }}</span></p>
                        </div>
                    {% else %}
                        <div class="item">
                        <p>{{ field.label_tag }} {{ field }}</p>
                        <p style="">&nbsp; &nbsp; &nbsp;<a class="delete" href="#">Delete</a></p>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
            
            <p style="text-align: center"><a id="add" href="#">Add team</a></p>
            <p><input type="submit" value=" Submit " class="login" /></p>
            </form>

        </div>

		<div class="col4 right">
			
			<h2 class="label label-orange">Latest leagues</h2><br />
			
			{% for league in last_leagues %}
                <p><img src="{{ league.country.flag }}"> <a href="{% url 'leagues:detail' league.id %}">{{ league.name }}</a> - {{ league.teams }} teams<br /><span class=" quiet small"> ~ (created: {{ league.created|date:"d.m.Y H:i" }})</span></p>
            {% endfor %}

			<p><a href="{% url 'leagues:latest' %}" class="more">Show more &raquo;</a></p>

		</div>

		<div class="clearer">&nbsp;</div>

	</div>

{% endblock %}